=========================
task1_deployment_k8s.yaml
=========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-get-image-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task1-app
  template:
    metadata:
      labels:
        app: task1-app
    spec:
      containers:
      - name: task1-container
        image: task1:frontend
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          valueFrom: 
              configMapKeyRef: 
                  name: webappdb-configmap  #___________  # 🎃 must match
                  key: database_host  
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
    name: webapp-task1-service  
    selector:  
        app: task1-app
    type: LoadBalancer  #We want this exposed to the outside world
    ports:
      - protocol: TCP
        port: 8083
        targetPort: 8083
        nodePort: 30000